### ISSUE TITLE
CORS connection error on search

### ISSUE THREAD

**Issue by blbrd** [Yam1337/Wikipedia-API#1]
It seems that there is an error when connecting to the Wikipedia api.
https://yam1337.github.io/Wikipedia-API/

`Access to XMLHttpRequest at 'https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&srsearch=co%C5%9B' from origin 'https://yam1337.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

To omit the CORS blockers add `&origin=*` to the fetched url.

**Comment by Yam1337** [comment]
Query param added, problem solved. New version deployed at [https://yam1337.github.io/Wikipedia-API/](https://yam1337.github.io/Wikipedia-API/)
